version: '3.8'
services:
  cinema-service:
    build: ./cinema-service # Path to Dockerfile for this service
    ports:
      - "8081:8080"  # Maps host port 8081 to container port 8080
    volumes:
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
#     - SPRING_PROFILES_ACTIVE=local
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=cinema-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - KC_HOSTNAME=keycloak
      - KC_HTTP_PORT=8080
  movie-service:
    build: ./movie-service
    ports:
      - "8082:8080"
    volumes:
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
#      - SPRING_PROFILES_ACTIVE=local
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=movie-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - KC_HOSTNAME=keycloak
      - KC_HTTP_PORT=8080
  booking-service:
    build: ./booking-service
    ports:
      - "8083:8080"
    volumes:
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
#     - SPRING_PROFILES_ACTIVE=local
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar
      - OTEL_SERVICE_NAME=booking-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - KC_HOSTNAME=keycloak
      - KC_HTTP_PORT=8080
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"
      - "6831:6831/udp" # Jaeger agent UDP port

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --hostname-strict=false --hostname-strict-https=false --hostname=keycloak
#    command: start-dev --hostname-strict=false --hostname-strict-https=false --hostname=localhost
#    command: start-dev --hostname-strict=false --hostname-strict-https=false --hostname=0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  eureka-server:
#    image: springcloud/eureka
    build: ./eureka-server
    ports:
      - "8761:8761"

volumes:
  keycloak_data: